# This is a basic workflow to help you get started with Actions

name: Trecurity

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: main

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # Continuous Deployment
  cd:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job 
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@v1.2.2
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        NUXT_JWT_APP_TOKEN_SECRET: ${{ secrets.NUXT_JWT_APP_TOKEN_SECRET }}
        NUXT_JWT_CONTROLLER_TOKEN_SECRET: ${{ secrets.NUXT_JWT_CONTROLLER_TOKEN_SECRET }}
        NUXT_PUBLIC_RECAPTCHA_CLIENT_SITE_KEY: ${{ secrets.NUXT_PUBLIC_RECAPTCHA_CLIENT_SITE_KEY }}
        NUXT_RECAPTCHA_SERVER_SITE_KEY: ${{ secrets.NUXT_RECAPTCHA_SERVER_SITE_KEY }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        envs: DATABASE_URL, SMTP_USERNAME, SMTP_PASSWORD, NUXT_JWT_APP_TOKEN_SECRET, NUXT_JWT_CONTROLLER_TOKEN_SECRET, NUXT_PUBLIC_RECAPTCHA_CLIENT_SITE_KEY, NUXT_RECAPTCHA_SERVER_SITE_KEY, SENTRY_AUTH_TOKEN
        script: |
          cd /trecurity/Trecurity-Web-App
          git checkout main
          git pull origin main
          git status
          npm install
          npx prisma migrate deploy 
          npx prisma generate
          npm run build
          node prisma/seed.js
          pm2 restart ecosystem.config.cjs
          pm2 save